db_file: "bot.db"

bot_url: "https://t.me/getpocket_client_bot"

messages:
  response:
    start: "🤖 Привет! Я помогу тебе вести продажи.\n Использую для этого нейросети."
    unknown_command: "Я не знаю такой команды :("
    link_saved: "Ссылка успешно сохранена!"
    send_photo: "Отправьте фото товара 📷"
  error:
    default: "Произошла неизвестная ошибка."
